---
- name: install docker and dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-compose
    - python3-docker

- name: add docker group
  become: yes
  group:
    name: docker
    state: present

- name: add douglas to docker group
  become: yes
  user:
    name: douglas
    groups: docker
    append: yes

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

#- name: create directory for image downloads
#  become: yes
#  file:
#    path: /opt/docker/images
#    state: directory
#
#- name: download fedora image
#  become: yes
#  get_url:
#    url: https://dl.fedoraproject.org/pub/fedora/linux/releases/27/Docker/armhfp/images/Fedora-Docker-Base-27-1.6.armhfp.tar.xz
#    dest: /opt/docker/images/
#    checksum: sha256:1b7a9f0022214bba9e5001a83013d205be290c59185b8e1a13bd05e87d0209bb
#
#- name: extract fedora image
#  become: yes
#  command: unxz Fedora-Docker-Base-27-1.6.armhfp.tar.xz
#  args:
#    chdir: /opt/docker/images
#    creates: /opt/docker/images/Fedora-Docker-Base-27-1.6.armhfp.tar

# TODO(dmend): Figure out why this task fails
#- name: load fedora image
#  docker_image:
#    name: fedora
#    state: present
#    tag: 27
#    load_path: /opt/docker/images/Fedora-Docker-Base-27-1.6.armhfp.tar
