---
- name: install docker and dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - python3-docker-py

- name: add docker group
  become: yes
  group:
    name: docker
    state: present

- name: add douglas to docker group
  become: yes
  user:
    name: douglas
    groups: docker
    append: yes

- name: start docker service
  become: yes
  service:
    name: docker
    state: started

- name: create directory for image downloads
  become: yes
  file:
    path: /opt/docker/images
    state: directory

- name: download fedora image
  become: yes
  get_url:
    url: https://dl.fedoraproject.org/pub/fedora/linux/releases/26/Docker/armhfp/images/Fedora-Container-Minimal-Base-26-1.5.armhfp.tar.xz
    dest: /opt/docker/images/
    checksum: sha256:f2aa1e3cf1b70856d1ee7b215dc41a4e8dbd12c13f2e75b78c48cb589b815197

- name: extract fedora image
  become: yes
  command: unxz Fedora-Container-Minimal-Base-26-1.5.armhfp.tar.xz
  args:
    chdir: /opt/docker/images
    creates: /opt/docker/images/Fedora-Container-Minimal-Base-26-1.5.armhfp.tar

- name: load fedora image
  docker_image:
    name: fedora
    tag: 26
    load_path: /opt/docker/images/Fedora-Container-Minimal-Base-26-1.5.armhfp.tar
