---
- name: secure sshd
  copy:
    src: roles/common/files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: restart sshd

- name: install fail2ban
  package:
    name: fail2ban-firewalld
    state: latest
  notify: restart fail2ban

- name: install tuned
  package:
    name: tuned
    state: latest
  notify: restart tuned

- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - fail2ban
    - tuned
