---
- name: secure sshd
  copy:
    src: roles/common/files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: restart sshd

- name: install fail2ban
  package:
    name: fail2ban-firewalld
    state: latest
  notify: restart fail2ban

- name: enable fail2ban
  service:
    name: fail2ban
    enabled: yes
