---
- name: install workstation packages
  become: yes
  package:
    name: '{{ item }}'
  loop:
    - tmux
    - vim

- name: add home directories
  file:
    dest: /home/douglas/{{ item }}
    state: directory
  loop:
    - Downloads
    - Workspaces

- name: clone dotfiles repo
  git:
    repo: 'https://github.com/dmend/dotfiles.git'
    dest: /home/douglas/.dotfiles

- name: check existing bash config
  stat:
    path: /home/douglas/{{ item }}
  loop:
    - .bashrc
    - .bash_profile
  register: stats

- name: delete default bash config
  file:
    dest: /home/douglas/{{ item.item }}
    state: absent
  loop: "{{ stats.results }}"
  when: item.stat.exists and item.stat.isreg

- name: link dotfiles
  file:
    src: /home/douglas/.dotfiles/{{ item }}
    dest: /home/douglas/{{ item }}
    state: link
  loop:
    - .bashrc
    - .bash_profile
    - .gitconfig
    - .tmux.conf
    - .vimrc

- name: clone pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: /home/douglas/.pyenv

- name: clone pyenv-virtualenv
  git:
    repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
    dest: /home/douglas/.pyenv/plugins/pyenv-virtualenv
