---
- name: install podman
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - podman
    - cockpit-podman

- name: start podman socket (for cockpit)
  become: yes
  service:
    name: io.podman.socket
    state: started
    enabled: yes
