---
- hosts: all
  remote_user: "{{ username }}"
  tasks:
    - name: "copy authorized key for {{ username }}"
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', 'roles/common/files/authorized_keys') }}"

    - name: "enable nopasswd sudo for {{ username }}"
      become: yes
      template:
        src: roles/common/templates/010_username-nopasswd.j2
        dest: "/etc/sudoers.d/010_{{ username }}-nopasswd"
        owner: root
        group: root
        mode: 0440
        force: yes
        validate: 'visudo -cf %s'
